<a href="https://colab.research.google.com/github/Annie1710/arguments/blob/main/Selecting_and_Slicing_DAWP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from numpy.random import default_rng
rng = default_rng(1234)

mystery_array = (rng.integers(low=0, high=500, size=216)
                * rng.integers(low=0, high=500, size=216)
                ).reshape((6, 6, 6))

In [3]:
print(mystery_array)

[[[116382 151768 171071  29830  35020  63618]
  [  1352  60320  33810  22101   5628  27966]
  [  9131  12120 111612  44838 147312  91580]
  [ 43110  52924  44320  13860  24257 144400]
  [204288 156884  96922  37497 121471 116602]
  [228960  15134   1173 102026 128781   5661]]

 [[106518   1806 121746  85260 117608  10350]
  [ 19683 123783   7100 111890  27945  89975]
  [ 17810  13170  37736 130784  76983  10512]
  [106672  18620    768    481  69874  49875]
  [ 34768   1287  80625 100064    870 120009]
  [ 24081 209755 174924   5776 168019 145824]]

 [[ 17444  22841  75650  40420 215254   1333]
  [ 12292  77688  25585   6210 197976  16660]
  [ 76760 111538 138240 146888  54120  59220]
  [ 98792  94304 144774  82695 117312  87001]
  [   724  21298   9906   3277 216480   6700]
  [ 17000  22326  41976  13664  45820  40280]]

 [[140946 215688  35728  34125  11398 116820]
  [ 22140 100092 120600  60053   2041  40565]
  [122200  36208  18600  57462   4536   6060]
  [ 90558  20378   5412   35

In [7]:
print(mystery_array.ndim)

3


In [6]:
print(mystery_array [0,0,0])

116382


In [9]:
print(mystery_array [5,5,5])

25668


In [10]:
print(mystery_array [2,5,2])

41976


In [11]:
print(mystery_array [4,5])

[  6624  26892 149100  16720 154912  43290]


In [15]:
print(mystery_array [0,2, 3:6])

[ 44838 147312  91580]


In [ ]:
print(mystery_array [])